[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
faucet = "9kKrAJsk287onKUgcqAtYF5P8WF65uyWC9yuujxAjXMj"
molpha = "2byMSUvpsSHp3xw7M4QNm2y4PLbfmUELNJrj2qwWPyLM"

[programs.localnet]
faucet = "9kKrAJsk287onKUgcqAtYF5P8WF65uyWC9yuujxAjXMj"
molpha = "2byMSUvpsSHp3xw7M4QNm2y4PLbfmUELNJrj2qwWPyLM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
setup-faucet = "yarn setup-test-faucet"
test = "RUST_LOG=error yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
